# Generated by Django 3.2.12 on 2023-07-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttospeech',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='texttospeech',
            name='mp3_count_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
