# Generated by Django 3.2.12 on 2023-07-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230722_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttospeech',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
